### ISSUE TITLE
More information about "strategy-query"

### ISSUE THREAD

**Issue by jcabrerazuniga** [wcmc-its/ReCiter-PubMed-Retrieval-Tool#47]
The Readme file mentions the "strategy-query" through an example. Where can we find more information about this important parameter? some more examples? 

Thanks in advance

**Comment by paulalbert1** [comment]
How closely did you look at the Readme file? It contains GIFs of the different APIs and how they work. For most standard queries, I use the [/pubmed/query](https://github.com/wcmc-its/ReCiter-PubMed-Retrieval-Tool#search-using-pubmedquery) API. You just input whatever you would search in PubMed. Makes sense?

**Comment by jcabrerazuniga** [comment]
That picture shown one example using this strategy:

"strategy-query": "Bales ME[au]"

But, how a strategy is made, I mean if there are more details about the making of strategies to get more reliable results... 
this is not clear for me...

Thanks

**Comment by jcabrerazuniga** [comment]
That picture shown just one example using this strategy:


"strategy-query": "Bales ME[au]"

But, how a strategy is made, I mean if there are more details about the making of strategies ... this is not clear for me...
Thanks

________________________________

**Comment by paulalbert1** [comment]
I think you're getting hung up on the word "strategy." What are you trying to search for? The documentation contains a number of examples, but maybe I didn't anticipate your use case.

**Comment by jcabrerazuniga** [comment]
At https://github.com/wcmc-its/ReCiter-PubMed-Retrieval-Tool I can see some examples, but...
a) what is the purpose on the use of [ ]?
b) at:  "strategy-query": "10.1007/s12026-013-8413-z[doi]"
what is 10.1007/s12026-013-8413-z for and what rules I need to follow to create my own?
c) what means doi? au?

For an an author I am trying to find all his/her publications in pubmed but because of the nature of pubmed some unexpected results can appear and this is the reason I want to understand the rules used to create strategies so I can refine my searches according to our needs.

Thank you very much

**Comment by paulalbert1** [comment]
DOI is a document object identifier. It's assigned by the publisher. Some articles in PubMed don't have them, but they're often useful.

When you see `[doi]` or `[au]`, these are standard PubMed search tags. 
https://pubmed.ncbi.nlm.nih.gov/help/#search-tags

Your medical librarian probably knows all about these. 

If you post your exact problem with specifics, I can give you feedback.

**Comment by jcabrerazuniga** [comment]
thanks for your response... 
I am quite new (beginner) to this "search" engine and I do not know any medical librarian so this was making hard for me to understand the examples.
We have several Investigators for which we need to find their publications in PubMed. I do not know them at all so I wanted to understand this Reciter tool to find that data using just their first name, last name (which could be not enough). This is so far my "general" view of the problem. I deeply believe that somehow that "strategy" field is so important for me to understand and you just gave me a great tip with the search tags link. Thanks again.

**Comment by paulalbert1** [comment]
As an identity-driven system, ReCiter works best when you have some identity info about a person. Their department, colleagues, year of terminal degree, etc. Closing this issue for now.
